// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfYF6fDai1QndL5xfGeVn9m-5oBPoBDjE',
    appId: '1:845873944405:web:5b25f5cc15dd0d00d641dc',
    messagingSenderId: '845873944405',
    projectId: 'culturetalesstorydatadase',
    authDomain: 'culturetalesstorydatadase.firebaseapp.com',
    storageBucket: 'culturetalesstorydatadase.appspot.com',
    measurementId: 'G-QJ3SCWM73Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-cSAilB_0MAZv84JT434LMA5Xab0cf-U',
    appId: '1:845873944405:android:ebf3c30ec680a566d641dc',
    messagingSenderId: '845873944405',
    projectId: 'culturetalesstorydatadase',
    storageBucket: 'culturetalesstorydatadase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjAkhpXHBhs68Q0Pc5uFgononp_ImeIus',
    appId: '1:845873944405:ios:24614abc4c963f1ed641dc',
    messagingSenderId: '845873944405',
    projectId: 'culturetalesstorydatadase',
    storageBucket: 'culturetalesstorydatadase.appspot.com',
    iosBundleId: 'com.example.cultureTales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjAkhpXHBhs68Q0Pc5uFgononp_ImeIus',
    appId: '1:845873944405:ios:8f852f30c4b4fd86d641dc',
    messagingSenderId: '845873944405',
    projectId: 'culturetalesstorydatadase',
    storageBucket: 'culturetalesstorydatadase.appspot.com',
    iosBundleId: 'com.example.cultureTales.RunnerTests',
  );
}
